apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # TODO: Replace by username and push the changes to your fork
          - repoURL: git@github.com:fernandobalieiro/k8s-training.git
            path: charts/simple-app
            name: simple-app
            type: api
          - repoURL: git@github.com:fernandobalieiro/k8s-training.git
            path: charts/app-with-db
            name: app-with-db
            type: api
          - repoURL: git@github.com:fernandobalieiro/k8s-training.git
            path: charts/postgres
            name: postgres
            type: services
  template:
    metadata:
      name: '{{name}}'
      labels:
        type: '{{type}}'
    spec:
      project: default
      source:
        helm:
          valueFiles:
            - values.yaml
        repoURL: '{{repoURL}}'
        targetRevision: argocd # This is the name of the branch where we have our code
        #targetRevision: HEAD # This is the proper value when configuring it normally
        path: '{{path}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
